config/routes.rb
Galleryart::Application.routes.draw do
  get "pages/about"
  get "pages/contact"

  resources :disciplines
  resources :teachers
  resources :works

  root :to => "pages#home"

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
	#validaciones
	validates :namediscipline, :presence=>true
	
	#tipo de relacion
	has_many :works
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	#validaciones
	validates :nameteacher, :presence=>true
	
	#tipos de relaciones
	has_many :works # un teacher puede tener muchos works
end

app/models/work.rb
class Work < ActiveRecord::Base
# Paperclip
  has_attached_file :avatar,:styles => {:thumb=> "100x100#",:small  => "150x150>" }
      
	#validaciones
	validates :namework, :presence=>true
	validates :description , :length=> {:minimum=>1, :maximum=>200}
	validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']

	#tipos de relaciones
	belongs_to :teachers # una obra pertenece a un solo teacher
	belongs_to :disciplines
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  # GET /disciplines
  # GET /disciplines.xml
  def index
    @disciplines = Discipline.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @disciplines }
    end
  end

  # GET /disciplines/1
  # GET /disciplines/1.xml
  def show
    @discipline = Discipline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @discipline }
    end
  end

  # GET /disciplines/new
  # GET /disciplines/new.xml
  def new
    @discipline = Discipline.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @discipline }
    end
  end

  # GET /disciplines/1/edit
  def edit
    @discipline = Discipline.find(params[:id])
  end

  # POST /disciplines
  # POST /disciplines.xml
  def create
    @discipline = Discipline.new(params[:discipline])

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to(@discipline, :notice => 'Discipline was successfully created.') }
        format.xml  { render :xml => @discipline, :status => :created, :location => @discipline }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @discipline.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /disciplines/1
  # PUT /disciplines/1.xml
  def update
    @discipline = Discipline.find(params[:id])

    respond_to do |format|
      if @discipline.update_attributes(params[:discipline])
        format.html { redirect_to(@discipline, :notice => 'Discipline was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @discipline.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.xml
  def destroy
    @discipline = Discipline.find(params[:id])
    @discipline.destroy

    respond_to do |format|
      format.html { redirect_to(disciplines_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	
  end

  def teacher
  end

  def work
  end

  def contact
  end

  def about
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.xml
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.xml
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.xml
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.xml
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to(@teacher, :notice => 'Teacher was successfully created.') }
        format.xml  { render :xml => @teacher, :status => :created, :location => @teacher }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.xml
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to(@teacher, :notice => 'Teacher was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.xml
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to(teachers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index 	 
    @works = Work.all
     respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @teachers }
    end
  end


  def show
  end

  def edit
  end

  def new
   @work = Work.new
  end

  def create
    @work = Work.create( params[:work] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/disciplines/_form.html.erb
<%= form_for(@discipline) do |f| %>
  <% if @discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% @discipline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :namediscipline %><br />
    <%= f.text_field :namediscipline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editing discipline</h1>

<%= render 'form' %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<div id="content">
<h1>Listing disciplines</h1>
<table>
  <tr>
    <th>Namediscipline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disciplines.each do |discipline| %>
  <tr>
    <td><%= discipline.namediscipline %></td>
    <td><%= link_to 'Show', discipline %></td>
    <td><%= link_to 'Edit', edit_discipline_path(discipline) %></td>
    <td><%= link_to 'Destroy', discipline, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Discipline', new_discipline_path %>
</div>
<br />

app/views/disciplines/new.html.erb
<h1>New discipline</h1>

<%= render 'form' %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Namediscipline:</b>
  <%= @discipline.namediscipline %>
</p>


<%= link_to 'Edit', edit_discipline_path(@discipline) %> |
<%= link_to 'Back', disciplines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galleryart</title>
  <%= stylesheet_link_tag "style_gallery", :media=>'screen'%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
  <div id="header">
    <h1>GALLERY ART</h1>
  </div>
  <div id="navigation">
    <p><strong>Menu</strong></p>
    <ul>
      <li><%= link_to "Inicio",{:action=>"home", :controller=>"pages"}%></li>
      <li><%= link_to "Artistas", teachers_path %></li>
      <li><%= link_to "Obras", works_path %></li>
      <li><%= link_to "Disciplinas", disciplines_path %></li>
      <li><%= link_to "Contacto", {:action=>'contact',:controller=>'pages'} %></li>
    </ul>
  </div>
  <%= yield %>
  <br>
  <div id="footer">
    <p>by Liliana 2010</p>
  </div>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Lorem ipsum dolor sit amet, sectetu adip scing varius interdum incid unt quis, libero. Aenean mturpis. Maecenas hendrerit masa laoreet iaculipede mnisl ulamcorper.
Tellus er sodales enim, in tincidunt mauris in odio. Massa ac laoreet iaculipede nisl ullamcorpermassa, ac consectetuer feipsum eget pede. Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odio. massa ac laoreet iaculipede nisl ullamcorpermassa,consectetuer feipsum eget pede. Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odi. Maecenas hendrerit, massa ac laoreet iaculipedenisl ullamcorpermassa, ac consectetuer feipsum eget pede. Proin nunc. Donec massa. Nulla pulvinar, nisl ac convallis nonummy, tellus eros sodales enim, in tincidunt mauris in odio. massa ac laoreet iaculipede nisl ullamcorpermassa, ac consectetuer feipsum eget pede. Proin nunc. Donec massa. </p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div id="content">
<p><span class="capitalLetter">Galleryart</span> nace con la ilusión de dar a conocer el Arte por el Arte, dando cabida a todos los artistas que quieran exponer en ella.
Pretende mostrar a todo tipo de artistas, estilos y tendencias, promocionando y dando a conocer sus obras.
GALLERYART quiere ser un punto de encuentro de personas que aman el arte</p>
<p>En nuestra galería podrás promocionar y dar a mostras tus obras mas facilmente.
Visita nuestra coleccion de Arte, lugar que deseamos ir ampliando y publicando nuevas ediciones.
Grandes autores: GALLERYART ofrece información sobre autores contemporaneos de reconocido nivel en el mundo del arte.</p>
</div>

app/views/pages/teacher.html.erb
<h1>Pages#teacher</h1>
<p>Find me in app/views/pages/teacher.html.erb</p>

app/views/pages/work.html.erb
<h1>Pages#work</h1>
<p>Find me in app/views/pages/work.html.erb</p>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nameteacher %><br />
    <%= f.text_field :nameteacher %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<div id="content">
	<h1>Teachers</h1>
	<table>
	  <tr>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	
	<% @teachers.each do |teacher| %>
	  <tr>
	    <td><%= teacher.nameteacher %></td>
	    <td><%= link_to 'Show', teacher %></td>
	    <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
	    <td><%= link_to 'Destroy', teacher, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	<%= link_to 'New Teacher', new_teacher_path %>
	</table>
</div>
<br />

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nameteacher:</b>
  <%= @teacher.nameteacher %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/works/edit.html.erb
<h1>Works#edit</h1>
<p>Find me in app/views/works/edit.html.erb</p>
 <% form_for :work, @work, :url => work_path, :html => { :multipart => true } do |form| %>
    <%= form.file_field :avatar %>
  <% end %>

app/views/works/index.html.erb
<div id="content">
	<h1>Works</h1>
	<table>
	  <tr>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	
	<% @works.each do |work| %>
	  <tr>
	    <td><%= work.namework %></td>
	    <td><%= work.description %></td>
	    <td><%= work.discipline_id %></td>
	    <td><%= work.teacher_id %></td>
	    <td><%= work.price %></td>
	    <%= image_tag @work.avatar.url %>
      <%= image_tag @work.avatar.url(:thumb) %>
      <%= image_tag @work.avatar.url(:small) %>
	    <td><%= link_to 'Show', work %></td>
	    <td><%= link_to 'Edit', edit_work_path(work) %></td>
	    <td><%= link_to 'Destroy', work, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	<%= link_to 'New Work', new_work_path %>
	</table>
</div>
<br />

app/views/works/new.html.erb
<div id="wrapper">
    <div id="content">
      <h1>Nueva Obra</h1>
      <%= form_for(@work) do |f| %>
        <div class="field">
          <%= f.label :Obra %><br />
          <%= f.text_field :namework %>
        </div>
        <div class="field">
          <%= f.label :Descripcion%><br />
          <%= f.text_field :description %>
        </div>
        <div class="field">
          <%= f.label :Disciplina %><br />
          <%= f.collection_select :discipline_id, Discipline.find(:all), :id, :namediscipline, :prompt => "Seleccione una disciplina" %>
        </div>
        <div class="field">
          <%= f.label :Precio %><br />
          <%= f.text_field :price %>
        </div>
         <div class="field">
          <%= f.label :Artista %><br />
           <%= f.collection_select :teacher_id, Teacher.find(:all), :id, :nameteacher, :prompt => "Seleccione un Artista" %>
        </div>
        <div>
            <%= f.label :avatar, "Avatar" %>
            <%= f.file_field :avatar %>
        </div>
        <div class="actions">
          <%= f.submit "Guardar" %>
        </div>
      <% end %>
    </div>   
</div>

app/views/works/show.html.erb
<h1>Works#show</h1>
@work = Work.find(params[:id])
@title = @user.name
<%= image_tag @work.avatar.url %>
<%= image_tag @work.avatar.url(:thumb) %>
<%= image_tag @work.avatar.url(:small) %>

<p>Find me in app/views/works/show.html.erb</p>